-- 0012_cover_charge：開桌費 / お通し / テーブルチャージ。
--
-- 設計依據見 docs/dining-modes.md 第五節。市售產品有兩種模型：
--
--   商品模型（Airレジ、ユビレジ、USEN、Eats365、Loyverse）：一個普通商品 × 人數
--   設定模型（スマレジ）：`テーブルチャージ 円/人`，自動乘上入座人數
--
-- open-pos 走**商品模型**，因為它跟吃到飽的人頭費是同一個機制，不必再造一個：
-- 開桌費是一行明細，於是稅額拆分、收據、分帳、品項排行、廚房分區
-- 五件事全部自動適用。`order_items.line_origin = 'cover'` 在 0011 就留好了。
--
-- ★ 只存「哪一個商品」，不存金額。
--   金額是那個商品的售價，而它已經有完整的一套：規格（大人 / 小孩）、
--   平日假日價（price_rules）、稅別、廚房分區。在這裡再存一份金額，
--   就是在等哪一天兩邊不一樣 —— 而不一樣的那天沒有人會發現。
ALTER TABLE stores ADD COLUMN cover_charge_item_id TEXT REFERENCES items(id);
